apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-client-deployment
  labels:
    app: aws-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-client
  template:
    metadata:
      labels:
        app: aws-client
    spec:
      containers:
      - name: aws-client
        image: amazon/aws-cli
        command: ["tail","-f","/dev/null"]