---
  name: "test opt"
  
  on:
    workflow_dispatch:
  jobs:
    publish-chart:
      name: "publish charts"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - uses: hustcer/setup-nu@v3
          with:
            version: "*"
        - name: get time
          id: get-time
          shell: nu {0}
          run: |
            echo "time=1" | save --append $env.GITHUB_OUTPUT
            echo "timeYY=2" | save --append $env.GITHUB_OUTPUT
            echo "timeMM=3" | save --append $env.GITHUB_OUTPUT
            echo "timeDD=4" | save --append $env.GITHUB_OUTPUT
        - name: get time 1
          shell: nu {0}
          run: |
            let a = ${{ steps.get-time.output.time }}
            print $a
        - name: get time 1
          shell: nu {0}
          run: |
            let a = ${{ steps.get-time.output.timeYY }}
            print $a
        - name: get time 1
          shell: nu {0}
          run: |
            let a = ${{ steps.get-time.output.timeMM }}
            print $a
        - name: get time 1
          shell: nu {0}
          run: |
            let a = ${{ steps.get-time.output.timeDD }}
            print $a
